# Define que as regras a seguir se aplicam ao usuário 'joao53'
user joao53
# Permissão de ESCRITA (publicar mensagens).
# O '#' é um curinga que permite publicar em qualquer subtópico.
topic write joao53/pub/#
topic write joao53/bitdoglab/#
# Permissão de LEITURA (receber mensagens).
# O '#' permite se inscrever em qualquer subtópico.
topic read joao53/pub/#
topic read joao53/bitdoglab/#



