#Arquivo de configuração principal do Mosquitto
# Impede que configurações de um listener afetem outro
per_listener_settings true
# --- Listener 1: Porta Padrão (Sem Segurança) ---
# Usado para testes iniciais de conectividade.
listener 1883
allow_anonymous true
# --- Listener 2: Porta Segura com TLS-PSK ---
# Esta é a porta que usaremos para a comunicação segura com a BitDogLab.
listener 8883
psk_hint "hint-para-joao53"
# CAMINHOS ABSOLUTOS: Aponta para os arquivos de chave e de regras.
# Usar barras normais (/) é a prática recomendada, mesmo no Windows.
psk_file /etc/mosquitto/psk.txt
acl_file /etc/mosquitto/acl.conf
# Instrução crucial: Usa a 'identity' do cliente PSK como nome de usuário
# para checar as regras no arquivo acl.conf.
use_identity_as_username true
include_dir /etc/mosquitto/conf.d
